### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by robert-samuel07** [lussierc/latexTemplates#4]
Everything in the repository seems to just be mashed together, which could make the files hard to understand and map when there is eventually more code. To better organize the repository you could place some of these files into their own folders and when you add more programs the added folders will make organization much faster and more simple. This will also allow people who have never seen your code to better understand it's layout and the different program functions.

**Comment by lussierc** [comment]
Thanks, @robert-samuel07! I think that is a great idea and I will likely implement it soon!
